---
galaxy_info:
  author: youssef
  description: "Automates server provisioning with base packages, DevOps tools, and Docker setup."
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - 22.04


