---
common_packages:
  - git
  - curl
  - wget
  - vim
  - net-tools
  - htop
  - unzip
  - zip
  - tar
  - tree
  - ca-certificates
  - software-properties-common
  - gnupg
  - lsb-release

devops_tools:
  - python3
  - python3-pip
  - ansible
  - docker.io
  - docker-compose
  - make

